# --- !Ups

create table "brands" (
  "id" bigint generated by default as identity(start with 10) not null primary key,
  "name" varchar not null,
  "year" int not null
);


create table "products" (
  "id" bigint generated by default as identity(start with 100) not null primary key,
  "name" varchar not null,
  "price" int not null,
  "brand_id" bigint
);

create table "orders" (
  "id" bigint generated by default as identity(start with 100) not null primary key,
  "customer_id" bigint not null,
   "qty" int not null,
   "amount" int not null
);

create table "items" (
  "id" bigint generated by default as identity(start with 100) not null primary key,
  "order_id" bigint not null,
  "product_id" bigint not null,
  "brand_id" bigint not null,
   "price" int not null,
   "qty" int not null,
   "amount" int not null
);

create table "reviews" (
  "id" int generated by default as identity(start with 10) not null primary key,
  "title" varchar not null,
  "body" varchar not null
);

insert into "brands" ("id","name", "year") values (1,'Brand 1', 2010);
insert into "brands" ("id","name", "year") values (2,'Brand 2', 2011);
insert into "brands" ("id","name", "year") values (3,'Brand 3', 2012);
insert into "brands" ("id","name", "year") values (4,'Brand 4', 2013);
insert into "brands" ("id","name", "year") values (5,'Brand 5', 2014);


insert into "products" ("id", "name",   "price", "brand_id") values (1, 'Product 1', 2010, 1);
insert into "products" ("id", "name",  "price", "brand_id") values (2, 'Product 2', 2011, 1);
insert into "products" ("id", "name",  "price", "brand_id") values (3,'Product 3', 2012, 1);
insert into "products" ("id", "name",  "price", "brand_id") values (4, 'Product 4', 2013, 1);
insert into "products" ("id", "name",  "price", "brand_id") values (5, 'Product 5', 2014, 1);

insert into "reviews" ("id", "title",   "body") values (1, 'Product 1', 'good product');
insert into "reviews" ("id", "title",   "body") values (2, 'Product 1', 'value for money');

# --- !Downs

drop table "items" if exists;
drop table "orders" if exists;
drop table "products" if exists;
drop table "brands" if exists;
drop table "reviews" if exists;